fix(playwright): added step for actually installing playwright

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -125,6 +125,15 @@ EOF
 	rm -rf $buildpack_tmpdir $build_tmpdir $cache_tmpdir
 }
 
+install_playwright() {
+	topic "Install playwright"
+	playwright install
+
+	if [ $? -ne 0 ]; then
+		error "Could not install playwright"
+	fi
+}
+
 configure_export_env() {
     topic "Writing profile script"
     mkdir -p $BUILD_DIR/.profile.d
@@ -155,4 +164,5 @@ export_env_dir() {
 
 export_env_dir "$ENV_DIR" PLAYWRIGHT_BUILDPACK_BROWSERS
 install_system_deps
+install_playwright
 configure_export_env
